#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

export GNUTERM=qt

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/lib/ccache
  /usr/local/{bin,sbin}
  /home/mko/toolchains/myriad/mdk_release_16.06.5_general_purpose/tools/00.50.75.5/linux64/sparc-myriad-elf-4.8.2/bin
  /home/mko/toolchains/gcc-arm-embedded/5_2-2015q4-20151219/bin
  /home/mko/toolchains/bh3-pdsdk/011/sysroots/x86_64-angstromsdk-linux/usr/bin/arm-angstrom-linux-gnueabi
  /home/mko/bin
  /home/mko/src/tstools/bin
  /usr/local/cuda-6.5/bin
  /home/mko/android-studio/bin/
  /home/mko/src/pd1/pdrepos02/_build/x86_64/bin
  /home/mko/src/pd2/pdrepos02/_build/x86_64/bin
  /home/mko/src/pd3/pdrepos02/_build/x86_64/bin
  /home/mko/src/pd1/pdrepos02/scripts
  /home/mko/src/pd2/pdrepos02/scripts
  /home/mko/src/pd3/pdrepos02/scripts
  $path
)

hode=~/src/pd1/pdrepos02
skulder=~/src/pd2/pdrepos02
kne=~/src/pd3/pdrepos02

: ~hode ~skulder ~kne

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
